services:
  - type: web
    name: ai-sdr-copilot
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput"
    startCommand: "gunicorn sdr_copilot.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DB_ENGINE
        value: "django.db.backends.sqlite3"
