# Generated by Django 5.2.16 on 2026-07-30 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0002_alter_company_created_at_alter_company_industry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('cold_email', 'Cold Email'), ('follow_up', 'Follow-up Email'), ('linkedin', 'LinkedIn Direct Message'), ('call_script', 'Sales Call Script'), ('meeting_req', 'Meeting Request')], db_index=True, default='cold_email', max_length=50)),
                ('target_role', models.CharField(default='Decision Maker / VP of Sales', help_text='Target Persona Role', max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Email Subject Line or Title', max_length=255)),
                ('content', models.TextField(help_text='AI Generated Sales Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_messages', to='research.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outreach Message',
                'verbose_name_plural': 'Outreach Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
