# Generated by Django 5.2.16 on 2026-07-30 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'Standard SDR User')], default='user', help_text='User System Role', max_length=20)),
                ('job_title', models.CharField(blank=True, default='Sales Development Representative', max_length=255)),
                ('target_industry', models.CharField(blank=True, default='Software & SaaS', max_length=255)),
                ('preferred_tone', models.CharField(default='Professional & Consultative', max_length=50)),
                ('custom_openai_key', models.CharField(blank=True, help_text='User specific OpenAI API Key (optional override)', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
