# Generated by Django 5.2.16 on 2026-07-30 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Target Company Name', max_length=255)),
                ('website', models.URLField(blank=True, help_text='Company Website URL', max_length=500, null=True)),
                ('industry', models.CharField(blank=True, help_text='Industry Category', max_length=255, null=True)),
                ('user_description', models.TextField(blank=True, help_text='User provided business description', null=True)),
                ('overview', models.TextField(blank=True, help_text='AI Business Overview', null=True)),
                ('products', models.TextField(blank=True, help_text='AI Extracted Products & Services', null=True)),
                ('pain_points', models.TextField(blank=True, help_text='Possible Customer Pain Points', null=True)),
                ('sales_insights', models.TextField(blank=True, help_text='AI Generated Sales Insights', null=True)),
                ('email_outreach', models.TextField(blank=True, help_text='Personalized Email Draft', null=True)),
                ('linkedin_outreach', models.TextField(blank=True, help_text='LinkedIn Direct Message Draft', null=True)),
                ('cold_call_script', models.TextField(blank=True, help_text='Cold Outreach Call Pitch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
