# Generated by Django 5.2.16 on 2026-07-30 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document Title or Description', max_length=255)),
                ('file', models.FileField(help_text='Uploaded PDF File', upload_to='pdf_documents/')),
                ('file_name', models.CharField(help_text='Original PDF File Name', max_length=255)),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of text chunks created')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
